## WiFi Configuration for ESPHome
##
## Author: Tommaso Frazzetto <tommaso.frazzetto@gmail.com>
## Version: 1.0
##
## This file configures the WiFi settings for the ESPHome device.
##
## -- IMPORTANT --
## Remember to change the static IP address (if you use it)
## to avoid conflicts on the local network.
##
## See https://esphome.io/components/wifi.html for more details.

substitutions:
  network_gateway: 192.168.1.1 # The gateway IP address for the network.
  network_subnet: 255.255.255.0 # The subnet mask for the network.
  network_dns1: 1.1.1.1 # Primary DNS server.
  network_dns2: 9.9.9.9 # Secondary DNS server.
  wifi_ssid: -- YOU WIFI SSID -- # The SSID of the WiFi network.
  wifi_static_ip: 192.168.1.201 # The static IP address for the ESPHome device.
  ap_ssid: "${friendly_name} Fallback Hotspot" # The SSID for the fallback hotspot.
  api_port: "6053" # The port for the API.

wifi:
  ssid: $wifi_ssid # The SSID of the WiFi network.
  password: !secret wifi_password # The password for the WiFi network.
  manual_ip:
    static_ip: $wifi_static_ip # The static IP address for the ESPHome device.
    gateway: $network_gateway # The gateway IP address for the network.
    subnet: $network_subnet # The subnet mask for the network.
    dns1: $network_dns1 # Primary DNS server.
    dns2: $network_dns2 # Secondary DNS server.

  ap:
    ssid: $ap_ssid # The SSID for the fallback hotspot.
    password: !secret wifi_ap_password # The password for the fallback hotspot.

captive_portal: # Enables the captive portal feature.

api:
  password: !secret api_password # The password for the API.
  port: $api_port # The port for the API.

ota:
  - platform: esphome
    password: !secret ota_password # The password for OTA updates.
